# Generated by Django 4.0.5 on 2022-06-15 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('demo_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='دمولینک')),
                ('source_link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='آدرس لینک')),
                ('id', models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'بخش پروژه',
            },
        ),
    ]
