# Generated by Django 4.0.5 on 2022-06-15 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_projects', '0003_tag_project_created_project_vote_ratio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': ' بازبینی جدید', 'verbose_name_plural': 'بخش بازبینی'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'تگ', 'verbose_name_plural': ' بخش تگ ها'},
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='بدنه'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_projects.project', verbose_name='رابطه با بخش '),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Up vote'), ('down', 'Down Vote')], max_length=200, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام تگ'),
        ),
    ]
