# Generated by Django 4.0.5 on 2022-06-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_projects', '0005_alter_review_id_alter_review_project_alter_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='', verbose_name='تصویر'),
        ),
    ]
