# Generated by Django 4.0.5 on 2022-06-22 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_users', '0002_alter_profile_options'),
        ('dev_projects', '0006_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dev_users.profile', verbose_name='مالک'),
        ),
    ]
