# Generated by Django 4.0.5 on 2022-06-30 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_users', '0003_profile_location_skill'),
        ('dev_projects', '0007_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dev_users.profile', verbose_name='مالک پروژه'),
        ),
    ]
