# Generated by Django 4.0.5 on 2022-07-10 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_users', '0005_alter_profile_username'),
        ('dev_projects', '0008_alter_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created'], 'verbose_name': 'پروژه', 'verbose_name_plural': 'بخش پروژه'},
        ),
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dev_users.profile', verbose_name='صاحب'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
