# Generated by Django 4.0.5 on 2022-07-10 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_users', '0005_alter_profile_username'),
        ('dev_projects', '0009_alter_project_options_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_users.profile', verbose_name='صاحب'),
        ),
    ]
