# Generated by Django 4.0.5 on 2022-07-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev_users', '0006_alter_profile_options_message'),
        ('dev_projects', '0012_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_total', '-vote_ratio', 'title'], 'verbose_name': 'پروژه', 'verbose_name_plural': 'بخش پروژه'},
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev_users.profile', verbose_name='مالک پروژه'),
        ),
        migrations.AlterField(
            model_name='review',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev_projects.project', verbose_name='ارتباط با کدام دوره '),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'Up vote'), ('down', 'Down Vote')], max_length=200, verbose_name='رای مثبت یا منفی'),
        ),
    ]
