# Generated by Django 4.0.5 on 2022-06-22 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, verbose_name='ایمیل')),
                ('short_bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='معرفی کوتاه')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('profile_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/', verbose_name='عکس پروفایل')),
                ('social_github', models.CharField(blank=True, max_length=200, null=True, verbose_name='گیت هاب')),
                ('social_twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='توئیتر')),
                ('social_linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='لینکدین')),
                ('social_website', models.CharField(blank=True, max_length=200, null=True, verbose_name='وب سایت')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='یوزر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'بخش پروفایل',
            },
        ),
    ]
