# Generated by Django 4.0.5 on 2022-06-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'یوزر', 'verbose_name_plural': 'پروفایل'},
        ),
    ]
