# Generated by Django 4.0.5 on 2022-07-11 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dev_users', '0005_alter_profile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created'], 'verbose_name': 'یوزر', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام')),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='')),
                ('is_read', models.BooleanField(default=False, null=True)),
                ('body', models.TextField(verbose_name='')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='dev_users.profile', verbose_name='دریافت کننده ')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dev_users.profile', verbose_name='یوز ارسال کننده ')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ['is_read', 'created'],
            },
        ),
    ]
